"""Anthropometric humanoid — an ORIGINAL generated humanoid built from head-canon proportions and our OWN
parametric geometry (elliptical lofts via the realize_shape DSL), with ZERO copied real-robot meshes.

This is the winner of a 4-strategy render bake-off (the others: paneled exo-shell, tube-frame+actuators,
program-first revolve). The decisive finding: a body reads as HUMAN when its PROPORTIONS follow the classical
~7.5-head canon AND each part has a broad-front/shallow-side cross-section — which only an ELLIPTICAL LOFT
(width in y and depth in x varying independently along z) can express, not an axisymmetric revolve (which
gives an un-human barrel). Everything here is generated by us, not pasted from a real Unitree/Franka model
([[original-generation-mandate]]). Proportions derive from ONE number: the head height H.
"""

from __future__ import annotations

import math

from virturoid.schemas.gene import GeneSegment, RobotGene

_DOWN = (math.pi, 0.0, 0.0)        # mount_euler that hangs a limb straight down (-z world) off the torso


def _loft(sections):
    """An elliptical-loft geometry spec: sections = [(z, half_y, half_x), ...] in meters."""
    return {"family": "loft", "sections": [[float(z), float(hy), float(hx)] for z, hy, hx in sections]}


def _mech_link(length, r, *, vented=False):
    """A MECHANICAL limb link — a flat chamfered structural beam (deep fore-aft, slimmer laterally, like an
    Atlas/Optimus leg plate), NOT a smooth organic loft. The real datasheet motor housing (show_actuators) sits
    at the proximal joint; an optional row of lightening vents reads as a real robot bracket."""
    depth = max(0.01, r)
    width = max(0.008, 0.66 * r)
    geo = {"family": "extrude", "height": round(length, 4), "fillet": round(0.35 * width, 4),
           "chamfer": round(0.5 * width, 5),
           "profile": [[-depth, -width], [0.92 * depth, -width], [0.92 * depth, width], [-depth, width]]}
    if vented:
        n = max(2, min(4, int(length / max(1e-3, 3.0 * r))))
        geo["cutouts"] = [[0.0, 0.0, round((i + 0.7) * length / (n + 0.3), 4), round(0.2 * r, 4),
                           round(2.4 * width, 4), "y"] for i in range(n)]
    return geo


def _sensor_head(length, r):
    """A mechanical SENSOR-HEAD module (rounded chamfered box with a flat camera face), not an organic skull."""
    hw = max(0.02, 0.92 * r)
    return {"family": "extrude", "height": round(length, 4), "fillet": round(0.4 * hw, 4),
            "chamfer": round(0.3 * hw, 5),
            "profile": [[-hw, -hw], [hw, -0.85 * hw], [hw, 0.85 * hw], [-hw, hw]]}


def _torso_module(z0, z1, hx, hy, *, chamfer, fillet_frac=0.16, vents=0):
    """One boxy, chamfered structural MODULE of the torso (chest / waist band / pelvis / shoulder shelf) —
    spans local z=[z0, z1] (pelvis floor=0 .. neck base=torso_len), ``hx`` = half fore-aft depth, ``hy`` =
    half lateral width. A real humanoid torso is a STACK of machined modules (Atlas/Optimus/H1), not a smooth
    mannequin loft, so we compose the torso from these. ``vents`` bores that many lightening slots through the
    side (y) faces — reads as a real ventilated chassis."""
    h = max(0.01, z1 - z0)
    geo = {"family": "extrude", "height": round(h, 4), "fillet": round(fillet_frac * hx, 4),
           "chamfer": round(chamfer, 5),
           "profile": [[-hx, -hy], [hx, -hy], [hx, hy], [-hx, hy]],
           "at": (0.0, 0.0, round(z0, 4))}
    if vents:
        geo["cutouts"] = [[round(0.1 * hx, 4), 0.0, round((i + 1.0) * h / (vents + 1.0), 4),
                           round(0.16 * h / (vents + 1.0), 4), round(2.4 * hy, 4), "y"] for i in range(vents)]
    return geo


def build_anthropometric_humanoid(H: float = 0.205, *, dims: dict | None = None) -> RobotGene:
    """Generate an original humanoid from head-canon proportions. ``H`` = head height (m); total stature
    ~7.7 H. 8 actuated DOF (hips+knees, shoulders+elbows); welded head/hands/feet add anatomy, not DOF.
    Default rest pose (all joints 0) stands with arms hanging to mid-thigh and feet flat — a real stance.

    ``dims`` (optional, metres) NUDGES individual segment LENGTHS away from the head-canon default so the LLM
    intent can ask for unusual proportions (a long-reach arm, a compact torso) WITHOUT touching radii/axes/
    geometry — keys: torso_mm, upper_arm_mm, forearm_mm, thigh_mm, shin_mm. Radii stay H-proportional, so a
    nudged limb just gets longer/shorter; absent keys keep the canon default (so the body is byte-identical)."""
    d = dims or {}
    seg: list[GeneSegment] = []

    # --- TORSO (root): a STACK of machined modules (pelvis -> waist band -> chest -> shoulder shelf), not a
    # smooth mannequin loft — so it reads as a real humanoid robot chassis (Atlas/Optimus/H1). Local +z spans
    # pelvis (z=0) -> shoulder/neck line (z=torso_len). Front shallower than side (hx < hy) = human stance.
    # Physics stays the single capsule (radius waist_y); the compound is VISUAL-ONLY, booleaned into one part.
    torso_len = float(d.get("torso_mm") or 2.5 * H)
    sh_y, sh_x = 1.06 * H, 0.50 * H          # shoulder half-width / half-depth (broad front)
    chest_y, chest_x = 0.88 * H, 0.50 * H
    waist_y, waist_x = 0.66 * H, 0.42 * H
    hip_y, hip_x = 0.80 * H, 0.46 * H
    cham = 0.05 * H
    pelvis = _torso_module(0.00, 0.27 * torso_len, hip_x, hip_y, chamfer=cham, vents=2)        # hip block
    waist = _torso_module(0.25 * torso_len, 0.47 * torso_len, waist_x * 0.92, waist_y * 0.90,  # inset midriff
                          chamfer=0.8 * cham, fillet_frac=0.30)
    chest = _torso_module(0.44 * torso_len, 0.90 * torso_len, chest_x, chest_y, chamfer=cham, vents=2)
    shoulders = _torso_module(0.86 * torso_len, torso_len, sh_x, sh_y, chamfer=1.2 * cham, fillet_frac=0.22)
    # a raised central CHEST PLATE / sternum panel on the front (+x) face — the signature robot-chest detail
    sternum = {"family": "extrude", "height": round(0.30 * torso_len, 4), "fillet": round(0.10 * H, 4),
               "chamfer": round(0.04 * H, 5),
               "profile": [[-0.06 * H, -0.34 * chest_y], [0.06 * H, -0.34 * chest_y],
                           [0.06 * H, 0.34 * chest_y], [-0.06 * H, 0.34 * chest_y]],
               "at": (round(chest_x * 0.92, 4), 0.0, round(0.52 * torso_len, 4))}
    torso_geo = {"family": "compound", "parts": [pelvis, waist, chest, shoulders, sternum]}
    seg.append(GeneSegment(name="torso", parent=None, shape="capsule", length_m=torso_len,
                           radius_m=waist_y, mass_kg=18.0, joint_type=None, geometry=torso_geo))

    # --- NECK + HEAD (head = 1.0 H): short neck stub + a tapered ovoid skull (revolve is fine — a head is
    # ~circular in cross-section). Mounted on the torso top, so no thin floating stalk.
    neck_len = 0.30 * H
    seg.append(GeneSegment(name="neck", parent="torso", shape="cylinder", length_m=neck_len,
                           radius_m=0.30 * H, mass_kg=0.6, joint_type=None,
                           geometry={"family": "revolve", "profile": [[0.33 * H, 0.0], [0.30 * H, neck_len]]}))
    head_len, head_r = 0.9 * H, 0.40 * H
    seg.append(GeneSegment(name="head", parent="neck", shape="capsule", length_m=head_len, radius_m=head_r,
                           mass_kg=1.2, joint_type=None, geometry=_sensor_head(head_len, head_r)))

    # --- ARMS (shoulder->wrist ~3.3 H), hanging straight down to mid-thigh. The fat proximal deltoid section
    # overlaps the shoulder shelf so the arm fuses into the torso (no float gap).
    up_len = float(d.get("upper_arm_mm") or 1.48 * H)
    fore_len = float(d.get("forearm_mm") or 1.22 * H)
    hand_len = 0.62 * H
    up_r, fore_r, hand_r = 0.30 * H, 0.23 * H, 0.20 * H
    shoulder_z = -0.03 * torso_len
    for side, sy in (("l", 1.0), ("r", -1.0)):
        # shoulders sit WIDER than the hips and the arm ABDUCTS ~13deg outward (mount_euler tilt about +x) so it
        # hangs clear of the thigh instead of clipping into it; straight-down (_DOWN) put the arm into the leg.
        seg.append(GeneSegment(name=f"{side}_uparm", parent="torso", shape="capsule", length_m=up_len,
                               radius_m=up_r, mass_kg=1.8, joint_type="revolute", joint_axis=(0, 1, 0),
                               joint_lower=-3.0, joint_upper=3.0, actuator_torque_nm=18.0,
                               mount_offset=(0.0, sy * sh_y * 0.88, shoulder_z),
                               mount_euler=(math.pi + sy * 0.17, 0.0, 0.0),
                               geometry=_mech_link(up_len, up_r, vented=True)))
        seg.append(GeneSegment(name=f"{side}_forearm", parent=f"{side}_uparm", shape="capsule",
                               length_m=fore_len, radius_m=fore_r, mass_kg=1.0, joint_type="revolute",
                               joint_axis=(0, 1, 0), joint_lower=-2.6, joint_upper=0.0, actuator_torque_nm=12.0,
                               geometry=_mech_link(fore_len, fore_r)))
        seg.append(GeneSegment(name=f"{side}_hand", parent=f"{side}_forearm", shape="capsule",
                               length_m=hand_len, radius_m=hand_r, mass_kg=0.4, joint_type=None,
                               is_end_effector=(side == "r"),
                               geometry={"family": "extrude", "height": round(hand_len, 4),
                                         "fillet": round(0.3 * hand_r, 4), "chamfer": round(0.25 * hand_r, 5),
                                         "profile": [[-hand_r, -0.66 * hand_r], [hand_r, -0.66 * hand_r],
                                                     [hand_r, 0.66 * hand_r], [-hand_r, 0.66 * hand_r]]}))

    # --- LEGS (thigh ~1.9 H, shin ~1.75 H): hips at the torso bottom, feet a forward-pointing sole.
    thigh_len = float(d.get("thigh_mm") or 1.9 * H)
    shin_len = float(d.get("shin_mm") or 1.75 * H)
    thigh_r, shin_r, ankle_r = 0.40 * H, 0.30 * H, 0.21 * H
    for side, sy in (("l", 1.0), ("r", -1.0)):
        seg.append(GeneSegment(name=f"{side}_thigh", parent="torso", shape="capsule", length_m=thigh_len,
                               radius_m=thigh_r, mass_kg=4.5, joint_type="revolute", joint_axis=(0, 1, 0),
                               joint_lower=-2.2, joint_upper=2.2, actuator_torque_nm=42.0,
                               mount_offset=(0.0, sy * hip_y * 0.74, -torso_len), mount_euler=_DOWN,
                               geometry=_mech_link(thigh_len, thigh_r, vented=True)))
        seg.append(GeneSegment(name=f"{side}_shin", parent=f"{side}_thigh", shape="capsule", length_m=shin_len,
                               radius_m=shin_r, mass_kg=2.6, joint_type="revolute", joint_axis=(0, 1, 0),
                               joint_lower=0.0, joint_upper=2.4, actuator_torque_nm=30.0,
                               geometry=_mech_link(shin_len, shin_r)))
        foot_len, foot_w, foot_h = 1.0 * H, 0.34 * H, 0.16 * H
        # The shin frame hangs down (+z = world -z); R_x(pi) makes the foot's sole lie FLAT — its forward (+x)
        # = world forward and its up (+z) = world up — instead of the old (0,-pi/2,0) that tipped the toe
        # downward and rendered the foot vertical.
        # push the foot DOWN past the shin's fat capsule hemisphere (which extends shin_r below the ankle) so the
        # FOOT — not the invisible shin collider — is the lowest contact; otherwise grounding lands on the shin
        # and the visible feet float ~shin_r above the floor.
        seg.append(GeneSegment(name=f"{side}_foot", parent=f"{side}_shin", shape="box", length_m=foot_h,
                               radius_m=foot_w, mass_kg=0.6, joint_type=None, mount_euler=(math.pi, 0.0, 0.0),
                               mount_offset=(0.0, 0.0, shin_r),
                               geometry={"family": "sole", "length": foot_len, "width": foot_w,
                                         "height": foot_h, "heel": 0.30 * H}))

    return RobotGene(id="humanoid_anthropometric", species="humanoid.anthropometric",
                     robot_class="humanoid", segments=seg, base_mount="free",
                     end_effector_type="none", metadata={})
