from __future__ import annotations

from dataclasses import dataclass, field
from typing import Protocol

from virturoid.schemas.training_result import TrainingEpisodeTrace


@dataclass(frozen=True)
class EpisodeBatchRequest:
    backend: str
    adapter_name: str
    purpose: str
    scene_artifact: str
    scenes: list[dict]
    planned_episodes: int
    policy_id: str
    start_index: int
    target_success_rate: float
    observation_keys: list[str]
    action_trace: list[str]
    compiled_scene_xml_by_scene_id: dict[str, str] = field(default_factory=dict)


class SimulatorAdapter(Protocol):
    name: str

    def run_episode_batch(self, request: EpisodeBatchRequest) -> list[TrainingEpisodeTrace]:
        """Return trace rows for a batch of training/evaluation episodes."""


class DryRunSimulatorAdapter:
    """Deterministic runner-shaped adapter used before a physics backend is wired."""

    name = "dry_run.synthetic_v0"

    def run_episode_batch(self, request: EpisodeBatchRequest) -> list[TrainingEpisodeTrace]:
        traces: list[TrainingEpisodeTrace] = []
        for local_index in range(request.planned_episodes):
            scene = request.scenes[local_index % len(request.scenes)]
            global_index = request.start_index + local_index
            success_probability = _synthetic_success_probability(request.target_success_rate, local_index)
            traces.append(
                TrainingEpisodeTrace(
                    episode_id=_episode_id(request.purpose, global_index),
                    backend=request.backend,
                    adapter_name=request.adapter_name,
                    purpose=request.purpose,
                    scene_id=scene["id"],
                    scene_artifact=request.scene_artifact,
                    policy_id=request.policy_id,
                    status="success" if success_probability >= 0.7 else "needs_review",
                    reward=round(success_probability * 100, 2),
                    success_probability=success_probability,
                    compiled_scene_xml_uri=request.compiled_scene_xml_by_scene_id.get(scene["id"], ""),
                    observation_keys=list(request.observation_keys),
                    action_trace=list(request.action_trace),
                    notes=[
                        "Synthetic trace generated by dry-run simulator adapter.",
                        "Replace this adapter with MuJoCo, Isaac, or another simulator backend.",
                    ],
                )
            )
        return traces


def default_simulator_adapter(backend: str) -> SimulatorAdapter:
    if backend == "mujoco":
        return DryRunSimulatorAdapter()
    return DryRunSimulatorAdapter()


def _synthetic_success_probability(target_success_rate: float, local_index: int) -> float:
    return round(max(0.0, min(1.0, target_success_rate - (local_index % 4) * 0.015)), 3)


def _episode_id(purpose: str, index: int) -> str:
    return f"episode_{purpose}_{index:04d}"
