import tempfile
import unittest
import json
from pathlib import Path
from xml.etree import ElementTree

from virturoid.mvp import build_mvp_robot_arm_project, write_mvp_robot_arm_project
from virturoid.services.package_validator import validate_mvp_export_package


class MvpRobotArmTests(unittest.TestCase):
    def test_mvp_builds_robot_arm_and_training_scene_set(self):
        project = build_mvp_robot_arm_project()

        self.assertEqual("fixed_arm.three_dof.tabletop", project["robot_genome"].species)
        self.assertGreaterEqual(len(project["selected_components"]), 4)
        self.assertGreaterEqual(len(project["cad_models"]), 5)
        self.assertEqual("pick_place_sort", project["task_graph"].task_type)
        self.assertEqual(2, len(project["baseline_scene_set"].scenes))
        self.assertEqual(10, len(project["scene_set"].scenes))
        self.assertEqual("variation", project["scene_set"].purpose)
        self.assertEqual(3, len(project["edge_case_scene_set"].scenes))       # activated edge_case difficulty
        self.assertEqual("edge_case", project["edge_case_scene_set"].purpose)
        self.assertGreaterEqual(len(project["regression_scene_set"].scenes), 1)
        self.assertEqual("regression", project["regression_scene_set"].purpose)
        self.assertEqual(3, len(project["holdout_scene_set"].scenes))
        self.assertGreaterEqual(project["training_manifest"].total_scene_count, 20)   # the plan's >=20 bar
        self.assertEqual(
            {"baseline", "variation", "edge_case", "regression", "holdout"},
            {group.purpose for group in project["training_manifest"].scene_groups},
        )

    def test_mvp_artifacts_validate(self):
        project = build_mvp_robot_arm_project()

        for key in [
            "requirements",
            "morphology_template",
            "builder_dispatch",
            "robot_build_blueprint",
            "part_resolution",
            "fabrication_plan",
            "bom",
            "power_architecture",
            "cad_assembly",
            "robot_genome",
            "task_graph",
            "baseline_scene_set",
            "scene_set",
            "regression_scene_set",
            "holdout_scene_set",
            "perception_config",
            "world_model_contract",
            "training_manifest",
            "training_objective",
            "training_run_config",
            "revised_training_run_config",
            "policy",
            "policy_plan",
            "evaluation_run",
            "export_bundle",
        ]:
            result = project[key].validate()
            self.assertTrue(result.ok, f"{key} failed validation: {result.issues}")

        for cad_model in project["cad_models"]:
            result = cad_model.validate()
            self.assertTrue(result.ok, f"{cad_model.id} failed validation: {result.issues}")

    def test_mvp_produces_failure_feedback_for_redesign_loop(self):
        project = build_mvp_robot_arm_project()
        evaluation_run = project["evaluation_run"]

        # the MVP now evaluates with REAL MuJoCo physics (not the synthetic mock), and the STRESS tier surfaces
        # genuine failures (objects past the reliable grasp envelope + heavy) for the redesign loop to act on.
        self.assertEqual("mujoco", evaluation_run.backend)
        self.assertGreaterEqual(len(evaluation_run.failures), 1)
        self.assertTrue(evaluation_run.failures[0].regression_scene_id)
        self.assertTrue(evaluation_run.failures[0].suggested_fixes)        # a real, specific fix (not a stub)
        self.assertIn(evaluation_run.failures[0].failure_type,
                      {"missed_grasp", "wrong_bin", "dropped", "instability", "unknown"})
        regression_scene = project["regression_scene_set"].scenes[0]
        self.assertIn("regression_from_evaluation", regression_scene.requirement_trace)
        # regression scenes are now FAILURE-CONDITIONED (plan §31.5): a targeted one-variable counterfactual
        # keyed on the failure type, not a generic 'bin_spacing: wider' stamp on every scene.
        vp = regression_scene.variation_parameters
        self.assertEqual(evaluation_run.failures[0].failure_type, vp["failure_type"])
        self.assertIn("counterfactual", vp)
        self.assertIn("changed_variable", vp)

    def test_mvp_writes_export_files(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = write_mvp_robot_arm_project(Path(tmpdir) / "mvp_robot_arm")

            self.assertTrue((output_dir / "manifest.json").exists())
            self.assertTrue((output_dir / "project.json").exists())
            self.assertTrue((output_dir / "design" / "morphology_template.json").exists())
            self.assertTrue((output_dir / "design" / "builder_dispatch.json").exists())
            self.assertTrue((output_dir / "design" / "robot_build_blueprint.json").exists())
            self.assertTrue((output_dir / "bom" / "bom.json").exists())
            self.assertTrue((output_dir / "bom" / "part_resolution_report.json").exists())
            self.assertTrue((output_dir / "cad" / "build_plan.json").exists())
            self.assertTrue((output_dir / "cad" / "parametric" / "robot_arm.py").exists())
            self.assertTrue((output_dir / "power" / "power_architecture.json").exists())
            self.assertTrue((output_dir / "robot" / "robot_genome.json").exists())
            self.assertTrue((output_dir / "robot" / "robot.urdf").exists())
            self.assertTrue((output_dir / "simulation" / "baseline_scene_set.json").exists())
            self.assertTrue((output_dir / "simulation" / "scene_set.json").exists())
            self.assertTrue((output_dir / "simulation" / "regression_scene_set.json").exists())
            self.assertTrue((output_dir / "simulation" / "holdout_scene_set.json").exists())
            self.assertTrue((output_dir / "simulation" / "revision_scene_set.json").exists())
            self.assertTrue((output_dir / "simulation" / "perception_config.json").exists())
            self.assertTrue((output_dir / "simulation" / "world_model_contract.json").exists())
            self.assertTrue((output_dir / "datasets" / "synthetic_observation_manifest.json").exists())
            self.assertTrue((output_dir / "datasets" / "synthetic_observations" / "index.json").exists())
            self.assertTrue((output_dir / "simulation" / "world_state_index.json").exists())
            self.assertTrue((output_dir / "simulation" / "simulator_contract.json").exists())
            self.assertTrue((output_dir / "simulation" / "mujoco" / "mvp_scene.xml").exists())
            self.assertTrue((output_dir / "simulation" / "mujoco" / "compiled_scene_index.json").exists())
            self.assertTrue((output_dir / "simulation" / "previews" / "index.html").exists())
            self.assertTrue((output_dir / "simulation" / "previews" / "variation_scene.svg").exists())
            self.assertTrue((output_dir / "training" / "training_manifest.json").exists())
            self.assertTrue((output_dir / "training" / "training_objective.json").exists())
            self.assertTrue((output_dir / "training" / "training_curriculum.json").exists())
            self.assertTrue((output_dir / "training" / "training_run_config.json").exists())
            self.assertTrue((output_dir / "training" / "training_run_config_revised.json").exists())
            self.assertTrue((output_dir / "training" / "training_run_config_next.json").exists())
            self.assertTrue((output_dir / "training" / "active_training_inputs.json").exists())
            self.assertTrue((output_dir / "software" / "policy_plan.json").exists())
            self.assertTrue((output_dir / "software" / "policy_plan_revised.json").exists())
            self.assertTrue((output_dir / "runs" / "mvp_training" / "dry_run_result.json").exists())
            self.assertTrue((output_dir / "runs" / "mvp_training" / "replay_index.json").exists())
            self.assertTrue((output_dir / "runs" / "mvp_training" / "logs" / "episode_trace.jsonl").exists())
            self.assertTrue((output_dir / "runs" / "mvp_training_revision" / "dry_run_result.json").exists())
            self.assertTrue((output_dir / "runs" / "mvp_training_revision" / "replay_index.json").exists())
            self.assertTrue((output_dir / "runs" / "mvp_training_revision" / "logs" / "episode_trace.jsonl").exists())
            self.assertTrue((output_dir / "runs" / "mvp_training_next" / "dry_run_result.json").exists())
            self.assertTrue((output_dir / "runs" / "mvp_training_next" / "replay_index.json").exists())
            self.assertTrue((output_dir / "runs" / "mvp_training_next" / "logs" / "episode_trace.jsonl").exists())
            self.assertTrue((output_dir / "software" / "ros2_test_harness_placeholder.json").exists())
            self.assertTrue((output_dir / "reports" / "mvp_evaluation_report.json").exists())
            self.assertTrue((output_dir / "reports" / "training_feedback.json").exists())
            self.assertTrue((output_dir / "reports" / "redesign_revision.json").exists())
            self.assertTrue((output_dir / "reports" / "improvement_report.json").exists())
            self.assertTrue((output_dir / "reports" / "promotion_decision.json").exists())
            self.assertTrue((output_dir / "reports" / "package_validation_report.json").exists())
            self.assertTrue((output_dir / "reports" / "mvp_summary.md").exists())
            self.assertTrue((output_dir / "reports" / "index.html").exists())
            self.assertTrue((output_dir / "cad" / "exact" / "robot_assembly.step").exists())
            self.assertIn(
                "Virturoid MVP placeholder STEP assembly",
                (output_dir / "cad" / "exact" / "robot_assembly.step").read_text(encoding="utf-8"),
            )
            robot_urdf = (output_dir / "robot" / "robot.urdf").read_text(encoding="utf-8")
            self.assertIn('<robot name="Autonomous reference tabletop arm">', robot_urdf)
            self.assertIn('<joint name="base_yaw" type="revolute">', robot_urdf)
            mujoco_xml = (output_dir / "simulation" / "mujoco" / "mvp_scene.xml").read_text(encoding="utf-8")
            self.assertIn('<mujoco model="Autonomous reference tabletop arm', mujoco_xml)
            self.assertIn('<worldbody>', mujoco_xml)
            self.assertIn('name="red_block"', mujoco_xml)
            compiled_scene_index = json.loads((output_dir / "simulation" / "mujoco" / "compiled_scene_index.json").read_text(encoding="utf-8"))
            simulator_contract = json.loads((output_dir / "simulation" / "simulator_contract.json").read_text(encoding="utf-8"))
            self.assertGreaterEqual(compiled_scene_index["scene_count"], 20)   # plan's >=20 bar (edge_case added)
            self.assertEqual(compiled_scene_index["scene_count"], len(simulator_contract["scene_contracts"]))
            self.assertTrue(all(scene["xml_parse_status"] == "pass" for scene in simulator_contract["scene_contracts"]))
            capability_by_backend = {item["backend"]: item for item in simulator_contract["backend_capabilities"]}
            self.assertTrue(capability_by_backend["dry_run"]["available"])
            self.assertIn(capability_by_backend["mujoco"]["status"], {"real_backend_available", "not_installed"})
            self.assertEqual(
                {"baseline", "variation", "edge_case", "regression", "holdout", "revision"},
                {entry["purpose"] for entry in compiled_scene_index["scenes"]},
            )
            first_scene_xml = output_dir / compiled_scene_index["scenes"][0]["mujoco_xml"]
            self.assertTrue(first_scene_xml.exists())
            self.assertEqual("mujoco", ElementTree.parse(first_scene_xml).getroot().tag)
            self.assertIn("scene_set_id=", first_scene_xml.read_text(encoding="utf-8"))
            preview_svg = (output_dir / "simulation" / "previews" / "variation_scene.svg").read_text(encoding="utf-8")
            self.assertIn("<svg", preview_svg)
            self.assertIn("red_block", preview_svg)
            stl_files = list((output_dir / "cad" / "mesh" / "visual").glob("*.stl"))
            self.assertGreaterEqual(len(stl_files), 5)
            self.assertIn("solid cad_arm_base", (output_dir / "cad" / "mesh" / "visual" / "cad_arm_base.stl").read_text(encoding="utf-8"))
            parametric_source = (output_dir / "cad" / "parametric" / "robot_arm.py").read_text(encoding="utf-8")
            self.assertIn("MODEL_PARAMETERS", parametric_source)
            self.assertIn("cad_upper_link", parametric_source)
            self.assertIn("ASSEMBLY_JOINTS", parametric_source)
            namespace = {}
            exec(compile(parametric_source, "robot_arm.py", "exec"), namespace)
            self.assertEqual(5, namespace["describe_build"]()["model_count"])
            dry_run = json.loads((output_dir / "runs" / "mvp_training" / "dry_run_result.json").read_text(encoding="utf-8"))
            morphology_template = json.loads((output_dir / "design" / "morphology_template.json").read_text(encoding="utf-8"))
            builder_dispatch = json.loads((output_dir / "design" / "builder_dispatch.json").read_text(encoding="utf-8"))
            blueprint = json.loads((output_dir / "design" / "robot_build_blueprint.json").read_text(encoding="utf-8"))
            training_run_config = json.loads((output_dir / "training" / "training_run_config.json").read_text(encoding="utf-8"))
            revised_training_run_config = json.loads((output_dir / "training" / "training_run_config_revised.json").read_text(encoding="utf-8"))
            next_training_run_config = json.loads((output_dir / "training" / "training_run_config_next.json").read_text(encoding="utf-8"))
            policy_plan = json.loads((output_dir / "software" / "policy_plan.json").read_text(encoding="utf-8"))
            self.assertEqual("software/policy_plan.json", training_run_config["policy_artifact"]["uri"])
            self.assertEqual("training/training_curriculum.json", training_run_config["curriculum_artifact"]["uri"])
            self.assertEqual("simulation/mujoco/compiled_scene_index.json", training_run_config["compiled_scene_artifact"]["uri"])
            self.assertEqual("software/policy_plan_revised.json", revised_training_run_config["policy_artifact"]["uri"])
            self.assertEqual("training/training_curriculum.json", revised_training_run_config["curriculum_artifact"]["uri"])
            self.assertEqual("simulation/mujoco/compiled_scene_index.json", revised_training_run_config["compiled_scene_artifact"]["uri"])
            self.assertEqual(["simulation/revision_scene_set.json"], [item["uri"] for item in revised_training_run_config["scene_artifacts"]])
            self.assertEqual("runs/mvp_training_revision", revised_training_run_config["output_dir"])
            self.assertEqual("runs/mvp_training_next", next_training_run_config["output_dir"])
            self.assertEqual("software/policy_plan_revised.json", next_training_run_config["policy_artifact"]["uri"])
            self.assertEqual("training/training_curriculum.json", next_training_run_config["curriculum_artifact"]["uri"])
            self.assertEqual("simulation/mujoco/compiled_scene_index.json", next_training_run_config["compiled_scene_artifact"]["uri"])
            self.assertEqual(["simulation/revision_scene_set.json"], [item["uri"] for item in next_training_run_config["scene_artifacts"]])
            self.assertEqual({"revision": 4}, next_training_run_config["episode_multiplier_overrides"])
            self.assertGreaterEqual(len(policy_plan["steps"]), 5)
            self.assertEqual("execute_place", policy_plan["steps"][-1]["step_id"])
            self.assertGreater(dry_run["total_planned_episodes"], 0)
            self.assertEqual("dry_run.synthetic_v0", dry_run["adapter_name"])
            self.assertEqual("manipulator", morphology_template["robot_class"])
            self.assertEqual("morph_fixed_arm_three_dof_tabletop", morphology_template["id"])
            self.assertEqual("implemented", builder_dispatch["dispatch_status"])
            self.assertEqual("morph_fixed_arm_three_dof_tabletop", builder_dispatch["selected_morphology_template_id"])
            self.assertEqual("virturoid.services.robot_arm_builder.build_reference_robot_arm", builder_dispatch["selected_builder_service"])
            self.assertGreaterEqual(len(builder_dispatch["planned_templates"]), 2)
            self.assertIn("mobile_base", (output_dir / "project.json").read_text(encoding="utf-8"))
            self.assertEqual("fixed_arm.three_dof.tabletop", blueprint["morphology"])
            self.assertEqual("manipulator", blueprint["robot_class"])
            self.assertEqual("morph_fixed_arm_three_dof_tabletop", blueprint["morphology_template_id"])
            self.assertIn("morph_fixed_arm_three_dof_tabletop", blueprint["candidate_morphology_template_ids"])
            self.assertIn("parametric_cad_generation", blueprint["required_builder_capabilities"])
            self.assertIn("scene_generation", {decision["area"] for decision in blueprint["decisions"]})
            self.assertIn("scene_to_training", {handoff["stage"] for handoff in blueprint["handoffs"]})
            self.assertTrue(
                all(
                    (output_dir / artifact["uri"]).exists()
                    for handoff in blueprint["handoffs"]
                    for artifact_group in ("inputs", "outputs")
                    for artifact in handoff[artifact_group]
                )
            )
            self.assertEqual("runs/mvp_training/replay_index.json", dry_run["replay_index_uri"])
            self.assertEqual("runs/mvp_training/logs/episode_trace.jsonl", dry_run["episode_trace_uri"])
            self.assertEqual(
                {"baseline", "variation", "edge_case", "regression", "holdout"},
                {group["purpose"] for group in dry_run["group_results"]},
            )
            replay_index = json.loads((output_dir / "runs" / "mvp_training" / "replay_index.json").read_text(encoding="utf-8"))
            self.assertEqual(dry_run["total_planned_episodes"], replay_index["episode_count"])
            self.assertEqual("dry_run.synthetic_v0", replay_index["adapter_name"])
            self.assertEqual("simulation/mujoco/compiled_scene_index.json", replay_index["compiled_scene_index_uri"])
            self.assertTrue(all((output_dir / uri).exists() for uri in replay_index["compiled_scene_xml_uris"]))
            perception_config = json.loads((output_dir / "simulation" / "perception_config.json").read_text(encoding="utf-8"))
            world_model = json.loads((output_dir / "simulation" / "world_model_contract.json").read_text(encoding="utf-8"))
            synthetic_manifest = json.loads((output_dir / "datasets" / "synthetic_observation_manifest.json").read_text(encoding="utf-8"))
            observation_index = json.loads((output_dir / "datasets" / "synthetic_observations" / "index.json").read_text(encoding="utf-8"))
            world_state_index = json.loads((output_dir / "simulation" / "world_state_index.json").read_text(encoding="utf-8"))
            self.assertEqual("simulation/perception_config.json", training_run_config["perception_artifact"]["uri"])
            self.assertEqual("training/training_objective.json", training_run_config["objective_artifact"]["uri"])
            self.assertEqual("simulation/perception_config.json", dry_run["perception_artifact_uri"])
            self.assertEqual("training/training_objective.json", dry_run["objective_artifact_uri"])
            self.assertEqual("training/training_curriculum.json", dry_run["curriculum_artifact_uri"])
            self.assertEqual("simulation/mujoco/compiled_scene_index.json", dry_run["compiled_scene_index_uri"])
            self.assertEqual(["wrist_rgbd_camera"], dry_run["observation_streams"])
            self.assertIn("red_sorted", dry_run["reward_terms"])
            self.assertIn("collision_penalty", dry_run["reward_terms"])
            self.assertEqual("rgbd_camera", perception_config["sensor_streams"][0]["sensor_type"])
            self.assertEqual(["rgb_image", "depth_image", "camera_intrinsics"], perception_config["sensor_streams"][0]["output_modalities"])
            self.assertIn("observations/wrist_rgbd_camera/depth.exr", perception_config["sensor_streams"][0]["simulated_outputs"])
            self.assertTrue(perception_config["vision_annotations"])
            self.assertIn("object_pose_6d", {item for spec in perception_config["vision_annotations"] for item in spec["annotation_modalities"]})
            self.assertEqual("datasets/synthetic_observations", perception_config["synthetic_dataset"]["output_root"])
            self.assertEqual(perception_config["id"], world_model["perception_config_id"])
            self.assertIn("world.object_poses", {item["key"] for item in world_model["state_variables"]})
            self.assertTrue(any(item["name"] == "link_geometry" for item in world_model["physical_parameter_targets"]))
            self.assertEqual("simulation/world_model_contract.json", synthetic_manifest["world_model_contract_uri"])
            self.assertEqual("datasets/synthetic_observations/index.json", synthetic_manifest["synthetic_observation_index_uri"])
            self.assertEqual("simulation/world_state_index.json", synthetic_manifest["world_state_index_uri"])
            self.assertGreaterEqual(observation_index["frame_count"], 18)        # grew with edge_case scenes
            self.assertEqual(observation_index["frame_count"], world_state_index["scene_state_count"])
            first_annotation = json.loads((output_dir / observation_index["frames"][0]["annotation_uri"]).read_text(encoding="utf-8"))
            self.assertTrue(first_annotation["annotations"])
            self.assertIn("bbox_xywh", first_annotation["annotations"][0])
            self.assertTrue((output_dir / world_state_index["scene_states"][0]["world_state_uri"]).exists())
            self.assertGreaterEqual(len(perception_config["texture_randomization"]), 3)
            part_resolution = json.loads((output_dir / "bom" / "part_resolution_report.json").read_text(encoding="utf-8"))
            parts_by_role = {item["role"]: item for item in part_resolution["resolved_parts"]}
            self.assertEqual("cmp_actuator_vx12", parts_by_role["joint_actuator"]["component_id"])
            self.assertEqual("requirement_recommendation", parts_by_role["joint_actuator"]["source"])
            self.assertEqual(50.0, parts_by_role["joint_actuator"]["technical_limits"]["no_load_speed_rpm"])
            self.assertEqual("cmp_camera_rgbd_mini", parts_by_role["wrist_sensor"]["component_id"])
            self.assertEqual("fixtures/cad/rgbd_mini.step", parts_by_role["wrist_sensor"]["cad_assets"][0]["uri"])
            fabrication_plan = json.loads((output_dir / "cad" / "build_plan.json").read_text(encoding="utf-8"))
            self.assertEqual("cad/parametric/robot_arm.py", fabrication_plan["parametric_source"]["uri"])
            self.assertEqual("cad/exact/robot_assembly.step", fabrication_plan["exact_assembly_artifact"]["uri"])
            self.assertGreater(fabrication_plan["estimated_printed_mass_kg"], 0)
            self.assertIn("cad_upper_link", fabrication_plan["generated_cad_parameters"])
            self.assertTrue(any(item["role"] == "joint_actuator" for item in fabrication_plan["part_cad_bindings"]))
            self.assertTrue(any(item["operation"] == "align_joint_axis" for item in fabrication_plan["assembly_operations"]))
            self.assertTrue(any(item["check"] == "reach_from_generated_links" for item in fabrication_plan["fabrication_checks"]))
            training_objective = json.loads((output_dir / "training" / "training_objective.json").read_text(encoding="utf-8"))
            objective_terms = {item["name"] for item in training_objective["reward_terms"]}
            self.assertIn("red_sorted", objective_terms)
            self.assertIn("all_sorted_bonus", objective_terms)
            self.assertTrue(any(item["terminal_status"] == "success" for item in training_objective["termination_rules"]))
            self.assertTrue(any(item["terminal_status"] == "failure" for item in training_objective["termination_rules"]))
            training_curriculum = json.loads((output_dir / "training" / "training_curriculum.json").read_text(encoding="utf-8"))
            self.assertEqual("simulation/mujoco/compiled_scene_index.json", training_curriculum["compiled_scene_index_uri"])
            self.assertEqual({"baseline", "variation", "edge_case", "regression", "holdout", "revision"}, {stage["purpose"] for stage in training_curriculum["stages"]})
            self.assertGreaterEqual(sum(stage["scene_count"] for stage in training_curriculum["stages"]), 20)
            self.assertGreater(sum(stage["planned_episodes"] for stage in training_curriculum["stages"]), 0)
            self.assertTrue(all((output_dir / binding["compiled_scene_xml_uri"]).exists() for stage in training_curriculum["stages"] for binding in stage["scene_bindings"]))
            self.assertIn("red_block inside red_bin", training_curriculum["success_checks"])
            self.assertIn("robot collides with forbidden object", training_curriculum["safety_checks"])
            training_feedback = json.loads((output_dir / "reports" / "training_feedback.json").read_text(encoding="utf-8"))
            self.assertEqual("needs_iteration", training_feedback["overall_status"])
            self.assertGreaterEqual(len(training_feedback["recommendations"]), 2)
            self.assertTrue(any(item["target"] == "policy" for item in training_feedback["recommendations"]))
            self.assertTrue(any(item["target"] == "scene_and_policy" for item in training_feedback["recommendations"]))
            revised_policy = json.loads((output_dir / "software" / "policy_plan_revised.json").read_text(encoding="utf-8"))
            revised_scene_set = json.loads((output_dir / "simulation" / "revision_scene_set.json").read_text(encoding="utf-8"))
            redesign_revision = json.loads((output_dir / "reports" / "redesign_revision.json").read_text(encoding="utf-8"))
            self.assertIn("recovery_waypoint", {step["step_id"] for step in revised_policy["steps"]})
            self.assertIn("pre_place_clearance", {step["step_id"] for step in revised_policy["steps"]})
            self.assertEqual("revision", revised_scene_set["purpose"])
            self.assertIn("revision_from_training_feedback", revised_scene_set["scenes"][0]["requirement_trace"])
            self.assertEqual("software/policy_plan_revised.json", redesign_revision["revised_policy_artifact"]["uri"])
            self.assertEqual("simulation/revision_scene_set.json", redesign_revision["revised_scene_artifact"]["uri"])
            self.assertGreaterEqual(len(redesign_revision["applied_recommendations"]), 2)
            revised_dry_run = json.loads((output_dir / "runs" / "mvp_training_revision" / "dry_run_result.json").read_text(encoding="utf-8"))
            revised_replay_index = json.loads((output_dir / "runs" / "mvp_training_revision" / "replay_index.json").read_text(encoding="utf-8"))
            revised_episode_lines = [
                json.loads(line)
                for line in (output_dir / "runs" / "mvp_training_revision" / "logs" / "episode_trace.jsonl")
                .read_text(encoding="utf-8")
                .splitlines()
                if line.strip()
            ]
            self.assertEqual(revised_training_run_config["id"], revised_dry_run["training_run_config_id"])
            self.assertEqual({"revision"}, {group["purpose"] for group in revised_dry_run["group_results"]})
            self.assertEqual(revised_dry_run["total_planned_episodes"], revised_replay_index["episode_count"])
            self.assertEqual(revised_dry_run["total_planned_episodes"], len(revised_episode_lines))
            self.assertIn("move_to_safe_lift_waypoint", revised_episode_lines[0]["action_trace"])
            self.assertIn("move_to_pre_place_clearance_pose", revised_episode_lines[0]["action_trace"])
            next_dry_run = json.loads((output_dir / "runs" / "mvp_training_next" / "dry_run_result.json").read_text(encoding="utf-8"))
            next_replay_index = json.loads((output_dir / "runs" / "mvp_training_next" / "replay_index.json").read_text(encoding="utf-8"))
            next_episode_lines = [
                json.loads(line)
                for line in (output_dir / "runs" / "mvp_training_next" / "logs" / "episode_trace.jsonl")
                .read_text(encoding="utf-8")
                .splitlines()
                if line.strip()
            ]
            self.assertEqual(next_training_run_config["id"], next_dry_run["training_run_config_id"])
            self.assertEqual({"revision"}, {group["purpose"] for group in next_dry_run["group_results"]})
            self.assertGreaterEqual(next_dry_run["total_planned_episodes"], 8)   # tracks the (larger) revision set
            self.assertEqual(next_dry_run["total_planned_episodes"], next_replay_index["episode_count"])
            self.assertEqual(next_dry_run["total_planned_episodes"], len(next_episode_lines))
            improvement_report = json.loads((output_dir / "reports" / "improvement_report.json").read_text(encoding="utf-8"))
            self.assertEqual("improved", improvement_report["outcome"])
            success_metric = next(item for item in improvement_report["metrics"] if item["name"] == "target_group_success_rate")
            self.assertGreater(success_metric["delta"], 0)
            self.assertEqual("original regression scene group vs revised scene group", improvement_report["comparison_basis"])
            promotion_decision = json.loads((output_dir / "reports" / "promotion_decision.json").read_text(encoding="utf-8"))
            active_inputs = json.loads((output_dir / "training" / "active_training_inputs.json").read_text(encoding="utf-8"))
            self.assertEqual("promote_revised_with_episode_warning", promotion_decision["decision"])
            self.assertTrue(promotion_decision["gates"]["success_improved"])
            self.assertTrue(promotion_decision["gates"]["scene_coverage_preserved"])
            self.assertEqual("training/training_run_config_revised.json", promotion_decision["selected_training_config"]["uri"])
            self.assertEqual("software/policy_plan_revised.json", promotion_decision["selected_policy_plan"]["uri"])
            self.assertEqual("simulation/revision_scene_set.json", promotion_decision["selected_scene_set"]["uri"])
            self.assertEqual(promotion_decision["id"], active_inputs["decision_id"])
            self.assertEqual("training/training_run_config_revised.json", active_inputs["training_config"]["uri"])
            episode_lines = [
                json.loads(line)
                for line in (output_dir / "runs" / "mvp_training" / "logs" / "episode_trace.jsonl")
                .read_text(encoding="utf-8")
                .splitlines()
                if line.strip()
            ]
            self.assertEqual(dry_run["total_planned_episodes"], len(episode_lines))
            self.assertEqual("episode_baseline_0001", episode_lines[0]["episode_id"])
            self.assertEqual("dry_run.synthetic_v0", episode_lines[0]["adapter_name"])
            self.assertEqual([step["command"] for step in policy_plan["steps"]], episode_lines[0]["action_trace"])
            self.assertTrue(episode_lines[0]["compiled_scene_xml_uri"].startswith("simulation/mujoco/scenes/baseline/"))
            self.assertTrue((output_dir / episode_lines[0]["compiled_scene_xml_uri"]).exists())
            summary = (output_dir / "reports" / "mvp_summary.md").read_text(encoding="utf-8")
            self.assertIn("# Virturoid MVP Robot Arm Summary", summary)
            self.assertIn("Autonomous reference tabletop arm", summary)
            self.assertIn("Robot Build Blueprint", summary)
            self.assertIn("Morphology Template", summary)
            self.assertIn("Builder Dispatch", summary)
            self.assertIn("design/robot_build_blueprint.json", summary)
            self.assertIn("design/morphology_template.json", summary)
            self.assertIn("design/builder_dispatch.json", summary)
            self.assertIn("Part Resolution", summary)
            self.assertIn("joint_actuator", summary)
            self.assertIn("no_load_speed_rpm=50.0", summary)
            self.assertIn("Fabrication Build Plan", summary)
            self.assertIn("cad/parametric/robot_arm.py", summary)
            self.assertIn("reach_from_generated_links", summary)
            self.assertIn("Perception Config", summary)
            self.assertIn("simulation/perception_config.json", summary)
            self.assertIn("simulation/world_model_contract.json", summary)
            self.assertIn("datasets/synthetic_observation_manifest.json", summary)
            self.assertIn("datasets/synthetic_observations/index.json", summary)
            self.assertIn("simulation/world_state_index.json", summary)
            self.assertIn("depth.exr", summary)
            self.assertIn("Training Objective", summary)
            self.assertIn("all_sorted_bonus", summary)
            self.assertIn("training/training_objective.json", summary)
            self.assertIn("Training Curriculum", summary)
            self.assertIn("training/training_curriculum.json", summary)
            self.assertIn("Scene Sets", summary)
            self.assertIn("Compiled MuJoCo Scenes", summary)
            self.assertIn("simulation/mujoco/compiled_scene_index.json", summary)
            self.assertIn("Simulator Contract", summary)
            self.assertIn("simulation/simulator_contract.json", summary)
            self.assertIn("Power Architecture", summary)
            self.assertIn("Battery estimate", summary)
            self.assertIn("Simulator adapter: dry_run.synthetic_v0", summary)
            self.assertIn("Policy plan: software/policy_plan.json", summary)
            self.assertIn("execute_place", summary)
            self.assertIn("Dry-run planned episodes", summary)
            self.assertIn("Training Feedback", summary)
            # the redesign feedback now acts on REAL physics failures (missed_grasp/dropped from the stress
            # tier), not a synthetic 'collision' — so a real failure-driven recommendation appears.
            self.assertTrue(any(s in summary for s in ("missed_grasp", "dropped", "wrong_bin", "instability")))
            self.assertIn("Redesign Revision", summary)
            self.assertIn("software/policy_plan_revised.json", summary)
            self.assertIn("simulation/revision_scene_set.json", summary)
            self.assertIn("Revised dry-run planned episodes", summary)
            self.assertIn("runs/mvp_training_revision/replay_index.json", summary)
            self.assertIn("Improvement Report", summary)
            self.assertIn("target_group_success_rate", summary)
            self.assertIn("Promotion Decision", summary)
            self.assertIn("promote_revised_with_episode_warning", summary)
            self.assertIn("training/active_training_inputs.json", summary)
            self.assertIn("Next Training Run", summary)
            self.assertIn("training/training_run_config_next.json", summary)
            self.assertIn("runs/mvp_training_next/replay_index.json", summary)
            self.assertIn("runs/mvp_training/replay_index.json", summary)
            self.assertIn("runs/mvp_training/logs/episode_trace.jsonl", summary)
            self.assertIn("reports/training_feedback.json", summary)
            self.assertIn("Package status: valid", summary)
            html = (output_dir / "reports" / "index.html").read_text(encoding="utf-8")
            self.assertIn("<title>Virturoid MVP Robot Arm Report</title>", html)
            self.assertIn("../robot/robot.urdf", html)
            self.assertIn("Robot Build Blueprint", html)
            self.assertIn("Morphology Template", html)
            self.assertIn("Builder Dispatch", html)
            self.assertIn("../design/robot_build_blueprint.json", html)
            self.assertIn("../design/morphology_template.json", html)
            self.assertIn("../design/builder_dispatch.json", html)
            self.assertIn("../simulation/mujoco/mvp_scene.xml", html)
            self.assertIn("Compiled MuJoCo Scenes", html)
            self.assertIn("../simulation/mujoco/compiled_scene_index.json", html)
            self.assertIn("Simulator Contract", html)
            self.assertIn("../simulation/simulator_contract.json", html)
            self.assertIn("../simulation/previews/index.html", html)
            self.assertIn("Part Resolution", html)
            self.assertIn("../bom/part_resolution_report.json", html)
            self.assertIn("Fabrication Build Plan", html)
            self.assertIn("../cad/build_plan.json", html)
            self.assertIn("../cad/parametric/robot_arm.py", html)
            self.assertIn("Perception Config", html)
            self.assertIn("../simulation/perception_config.json", html)
            self.assertIn("../simulation/world_model_contract.json", html)
            self.assertIn("../datasets/synthetic_observation_manifest.json", html)
            self.assertIn("../datasets/synthetic_observations/index.json", html)
            self.assertIn("../simulation/world_state_index.json", html)
            self.assertIn("Training Objective", html)
            self.assertIn("../training/training_objective.json", html)
            self.assertIn("Training Curriculum", html)
            self.assertIn("../training/training_curriculum.json", html)
            self.assertIn("../power/power_architecture.json", html)
            self.assertIn("../software/policy_plan.json", html)
            self.assertIn("Policy Plan", html)
            self.assertIn("Dry-Run Training Result", html)
            self.assertIn("Training Feedback", html)
            self.assertIn("training_feedback.json", html)
            self.assertIn("Redesign Revision", html)
            self.assertIn("redesign_revision.json", html)
            self.assertIn("../software/policy_plan_revised.json", html)
            self.assertIn("../simulation/revision_scene_set.json", html)
            self.assertIn("Revised Dry-Run Training Result", html)
            self.assertIn("Improvement Report", html)
            self.assertIn("improvement_report.json", html)
            self.assertIn("Promotion Decision", html)
            self.assertIn("promotion_decision.json", html)
            self.assertIn("../training/active_training_inputs.json", html)
            self.assertIn("Next Training Run", html)
            self.assertIn("../training/training_run_config_next.json", html)
            self.assertIn("../runs/mvp_training_next/replay_index.json", html)
            self.assertIn("../runs/mvp_training_revision/dry_run_result.json", html)
            self.assertIn("../runs/mvp_training/dry_run_result.json", html)
            self.assertIn("../runs/mvp_training/replay_index.json", html)
            self.assertIn("../runs/mvp_training/logs/episode_trace.jsonl", html)
            self.assertIn("dry_run.synthetic_v0", html)
            self.assertIn("Battery estimate", html)

    def test_mvp_export_package_validates(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = write_mvp_robot_arm_project(Path(tmpdir) / "mvp_robot_arm")
            report = validate_mvp_export_package(output_dir)
            report_file = json.loads((output_dir / "reports" / "package_validation_report.json").read_text(encoding="utf-8"))

            self.assertTrue(report.ok, report.checks)
            self.assertTrue(report_file["ok"])
            self.assertTrue(any(check.name == "urdf_xml" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "mujoco_xml" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "morphology_template_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "builder_dispatch_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "builder_dispatch_contract" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "robot_build_blueprint_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "robot_build_blueprint_references" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "compiled_scene_index_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "compiled_scene_index_references" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "part_resolution_report_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "fabrication_build_plan_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "fabrication_plan_references" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "parametric_cad_source_python" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "perception_config_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "perception_contract" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "world_model_contract_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "synthetic_observation_manifest_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "synthetic_observation_index_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "world_state_index_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "world_model_contract" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "synthetic_observation_dataset" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "simulator_contract_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "simulator_contract_references" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "training_run_config_revised_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "training_objective_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "training_objective_contract" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "training_curriculum_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "training_curriculum_references" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "training_run_config_next_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "active_training_inputs_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "policy_plan_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "policy_plan_revised_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "revision_scene_set_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "training_feedback_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "redesign_revision_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "improvement_report_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "promotion_decision_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "dry_run_result_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "revised_dry_run_result_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "next_dry_run_result_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "replay_index_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "revised_replay_index_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "next_replay_index_json" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "episode_trace_jsonl" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "revised_episode_trace_jsonl" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "next_episode_trace_jsonl" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "replay_index_references" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "revised_replay_index_references" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "next_replay_index_references" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "next_training_config_references" and check.status == "pass" for check in report.checks))
            self.assertTrue(any(check.name == "active_inputs_references" and check.status == "pass" for check in report.checks))

    def test_mvp_power_architecture_has_expected_rails(self):
        project = build_mvp_robot_arm_project()
        power = project["power_architecture"]

        self.assertTrue(power.validate().ok)
        self.assertEqual({"actuator_24v", "compute_12v", "sensor_5v"}, {rail.name for rail in power.rails})
        self.assertGreater(power.total_peak_current_a, 0)
        self.assertIsNotNone(power.battery)
        self.assertGreater(power.battery.estimated_runtime_minutes, 0)
        for rail in power.rails:
            self.assertGreaterEqual(rail.recommended_regulator_current_a, rail.estimated_peak_current_a)
            self.assertGreaterEqual(rail.headroom_percent, 0)


if __name__ == "__main__":
    unittest.main()
